export const errorMap = {
  // 🔹 Usuário
  USER_ALREADY_EXISTS: 409,
  USER_NOT_FOUND: 404,
  ACCOUNT_ALREADY_ACTIVE: 400,
  ACCOUNT_NOT_ACTIVE: 403,
  ACCOUNT_BLOCKED: 403,
  ACCOUNT_NOT_BLOCKED: 400,
  ACCOUNT_ACTIVATED: 200,
  ACCOUNT_UNLOCKED: 200,
  USER_CREATED: 201,
  USER_CREATED_EMAIL_FAILED: 201,
  DASHBOARD_LOADED: 200,
  NAME_UPDATED: 200,
  PASSWORD_CHANGED: 200,
  ACCOUNT_DELETED: 200,

  // 🔹 Autenticação
  LOGIN_SUCCESS: 200,
  INVALID_CREDENTIALS: 200,
  UNAUTHORIZED: 401,
  TWO_FACTOR_REQUIRED: 200,
  INVALID_CODE: 400,
  CODE_EXPIRED: 400,

  // 🔹 Sessões
  SESSION_ACTIVE: 200,
  SESSION_INACTIVE: 401,
  SESSION_EXPIRED: 401,

  // 🔹 Senhas
  PASSWORD_FIELDS_REQUIRED: 400,
  PASSWORD_MUST_BE_DIFFERENT: 400,
  PASSWORD_RESET_SUCCESS: 200,
  PASSWORD_RESET_EMAIL_SENT: 200,

  // 🔹 Google OAuth
  GOOGLE_TOKEN_REQUIRED: 400,
  GOOGLE_TOKEN_RECEIVED: 200,
  GOOGLE_LOGIN_ERROR: 500,

  // 🔹 E-mail
  EMAIL_REQUIRED: 400,
  EMAIL_NOT_SENT: 500,
  RESEND_EMAIL_SUCCESS: 200,
  RESEND_EMAIL_FAILED: 500,
  UNLOCK_EMAIL_SENT: 200,

  // 🔹 Tokens
  TOKEN_EXPIRED: 400,
  INVALID_TOKEN: 401,

  // 🔹 Validação / Segurança
  VALIDATION_ERROR: 400,
  TOO_MANY_REQUESTS: 429,

  // 🔹 Banco / Interno
  DATABASE_ACCESS_ERROR: 500,
  INTERNAL_ERROR: 500,
};
